# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'IsoThoughts' 
tagline:          It's a big world out there!'
description:      'We all do the best we can.'
url:              http://isothoughts.com
baseurl:          /

author:
  name:           'Andrew Robinson'
  url:            https://twitter.com/ab500

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ab500/ab500.github.io
